Update yaml config related
Kanazawanaoaki/jsk_learning_utils pull request #3
Opened 2022-04-08 11:35 UTC by Kanazawanaoaki

configのyaml関連の部分をupdateしました．

### 対応したこと
- yamlの階層化
- ジョイントのタイプによって変換方法を変える. (各ジョイントのタイプはyamlに書く.)
- from_ros_msg の 入出力の共通化 (型も共通化)　共通のConfigを入力にする
- 制御する関節角のconfig名の変更(control_joint_names -> control_joints)
- get_numpy() の入出力の共通化

2022-04-08 12:54 UTC, HiroIshida requested changes

2022-04-08 12:54 UTC, HiroIshida commented on scripts/rosbag_convert_to_data.py
> +                    joint_angles.append(msg.position[idx])
このように複数の条件分岐がある場合は, if, elif, else を使ったほうがよいです. その上で以下のように最後のelse でassert Falseをいれて, 考慮対象外のジョイントタイプが入力された場合にはプログラムを落とすようにしてください. 
if :
    hogehoge
elif :
    hogehoge
else:
    assert False, 'joint type {} is not expected'.format(joint_type)

https://codezine.jp/article/detail/12179 の　Pythonのアサーション構文  参照

2022-04-08 18:53 UTC, HiroIshida requested changes

2022-04-08 18:53 UTC, HiroIshida commented on scripts/rosbag_convert_to_data.py
> +    data: PIL.Image.Image
angle vectorの方と合わせるために data: np.ndarrayにしてほしいです. PILからnumpyの変換については 
https://stackoverflow.com/a/1095878

2022-04-08 18:53 UTC, HiroIshida commented on scripts/rosbag_convert_to_data.py
> +    def pil_image(self) -> PIL.Image.Image:
ここも numpy(self) -> np.ndarrayに

2022-04-08 22:00 UTC, HiroIshida commented
@Kanazawanaoaki 
あと, PRの変更が少ないときは, マージするときに Squash and Mergeすると, mainブランチのcommit logが汚くなりにくくておすすめです.

2022-04-09 07:21 UTC, Kanazawanaoaki commented on scripts/rosbag_convert_to_data.py
> +                    joint_angles.append(msg.position[idx])
ありがとうございます．確かにelifを使うべきですね．アサーションも追加しました．
https://github.com/Kanazawanaoaki/jsk_learning_utils/pull/3/commits/c6c8f39cc0fb8915ac7d49532653f4c45a04a23f

2022-04-09 07:24 UTC, Kanazawanaoaki commented
ありがとうございます．  
rebase -i を使ってローカルのcomit logは綺麗にできたのですが，force pushした為(rebaseの場合はforce push するしかない？)github上のlogは大変なことになってしまいました．  
ローカルでは，
```
$ git log
commit c6c8f39cc0fb8915ac7d49532653f4c45a04a23f (HEAD -> update-yaml-file)
Author: Kanazawa Naoaki <naoaki65k@gmail.com>
Date:   Sat Apr 9 15:51:04 2022 +0900

    Add assertion and use elif in processing joint type

commit 801f3cde1607e1a32b090fe85b248589b17d0b63
Author: Kanazawa Naoaki <naoaki65k@gmail.com>
Date:   Fri Apr 8 20:24:41 2022 +0900

    Update control joint config

commit e0008b6b5be5f94b222876914a7971152a5780d8
Author: Kanazawa Naoaki <naoaki65k@gmail.com>
Date:   Fri Apr 8 19:02:15 2022 +0900

    Add topic names in yaml config

commit 1cf30c70696f587c972aad7d0f48c6621f1dcbe0
Author: Kanazawa Naoaki <naoaki65k@gmail.com>
Date:   Fri Apr 8 18:18:47 2022 +0900

    Fix PIL image methods


```
とかなり綺麗になってはいます．

2022-04-09 07:54 UTC, HiroIshida commented
対応ありがとう
リベースするとforceオプションつきでpush するしかないのだけど, 基本的にはPRで出しているブランチは force して大丈夫です。
mainブランチとかでそれをやらかすと大変なことになりかねないので、しっかりしたレポジトリはmain/masterブランチ にはforce pushできないようになってます
https://qiita.com/kazuph/items/825d9d3ff9cacc279bbc

2022-04-09 08:38 UTC, merged